### ISSUE TITLE
Game crash's when connecting to Server

### ISSUE THREAD

**Issue by snoozyi** [Talon396/EnhancedWeather#59]
Couple days ago i hopped on my server and everything was working as expected. Today I tried connecting to it and the client keeps crashing when connects and this is what the client reports. 

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-05-28 17:23:09
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "sh.talonfox.enhancedweather.weather.ServersideManager.getClosestCloud(net.minecraft.class_243, double, boolean, boolean, boolean, boolean, int)" because "sh.talonfox.enhancedweather.EnhancedWeather.SERVER_WEATHER" is null
	at net.minecraft.class_1959.method_8696(class_1959.java:1526)
	at team.creative.ambientsounds.env.AmbientEnvironment.analyzeFast(AmbientEnvironment.java:54)
	at team.creative.ambientsounds.AmbientTickHandler.onTick(AmbientTickHandler.java:274)
	at team.creative.creativecore.CreativeFabricLoader.lambda$registerClientTick$1(CreativeFabricLoader.java:47)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$bfp000$fabric-lifecycle-events-v1$onEndTick(class_310.java:7473)
	at net.minecraft.class_310.method_1574(class_310.java:1907)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1959.method_8696(class_1959.java:1526)
	at team.creative.ambientsounds.env.AmbientEnvironment.analyzeFast(AmbientEnvironment.java:54)
	at team.creative.ambientsounds.AmbientTickHandler.onTick(AmbientTickHandler.java:274)
	at team.creative.creativecore.CreativeFabricLoader.lambda$registerClientTick$1(CreativeFabricLoader.java:47)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$bfp000$fabric-lifecycle-events-v1$onEndTick(class_310.java:7473)

-- Affected level --
Details:
	All players: 1 total; [class_746['TwT_Nyaa'/514, l='ClientLevel', x=-462.70, y=62.00, z=349.66]]
	Chunk stats: 1024, 157 F: 0 L: 468 U: 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,131,0), Section: (at 0,3,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 109801764 game time, 109182266 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 811275320 bytes (773 MiB) / 1568669696 bytes (1496 MiB) up to 8925478912 bytes (8512 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.69
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2520
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4629
	Graphics card #1 name: USB 3.0 External Graphic Device
	Graphics card #1 vendor: Magic Control Technology Corp. (0x0711)
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: 0x5621
	Graphics card #1 versionInfo: DriverVersion=1.5.2401.222
	Graphics card #2 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #2 vendor: Intel Corporation (0x8086)
	Graphics card #2 VRAM (MB): 1024.00
	Graphics card #2 deviceId: 0x46a6
	Graphics card #2 versionInfo: DriverVersion=31.0.101.3962
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 50253.13
	Virtual memory used (MB): 44326.54
	Swap memory total (MB): 9605.80
	Swap memory used (MB): 44.54
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8512m -Xms256m
	Fabric Mods: 
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		animated_guns: Simple Animated Guns 1.2
		architectury: Architectury 6.6.92
		attributefix: AttributeFix 17.2.8
		balm-fabric: Balm 4.6.0
		bobby: Bobby 4.0.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bookshelf: Bookshelf 16.3.20
		byg: Oh The Biomes You'll Go 2.0.1.6
		cave_dweller: Cave Dweller Fabric 1.3.0
		cavedust: Cave Dust 1.2.0
			kirin: Kirin UI 1.11.1-beta.1
		cloth-config: Cloth Config v8 8.3.115
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		connectivity: Connectivity Mod 1.19.2-4.5
		corgilib: CorgiLib 1.0.0.34
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		craftabletotemofundying: Craftable Totem Of Undying 1.19.2-1.6.3-[FABRIC]
		creativecore: CreativeCore (Fabric) 2.9.3
		cupboard: cupboard 1.19.2-2.6
		dusk: Dusk Mod 1.19.2-3.3
		dynview: Dynamic View Mod 1.19.1-2.3
		ears: Ears 1.4.6
		enchdesc: EnchantmentDescriptions 13.0.14
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.9
		enhancedweather: Enhanced Weather 1.0-Beta5
			blue_endless_jankson: jankson 1.2.0
		explorify-fabric: Explorify 1.19-1.3.0
		extraorigins: Extra Origins 1.19-2
		fabric-api: Fabric API 0.77.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.42+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.9+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.12+def3f86d90
			fabric-networking-v0: Fabric Networking (v0) 0.3.29+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+ee641e7390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.2+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.33+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.25+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.28+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.13.0+526f2c6790
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.8+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fallingleaves: Falling Leaves 1.13.0+1.19.2
		ferritecore: FerriteCore 5.0.3
		furorigins: Furry Origins 1.0.0
		geckoanimfix: GeckoLibIrisCompat 1.0.0
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		graveyard: The Graveyard 2.3.3
			omega-config: OmegaConfig 1.2.2-1.18.1
		grindenchantments: Grind Enchantments 3.1.1+1.19.2
			codec-config-api: Codec Config API 1.0.2+1.19.3
		handcrafted: Handcrafted 2.0.6
		iris: Iris 1.6.11
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 8.7.3
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.6.0.1019
		man: The Man from the Fog 1.1.1
			porting_lib_fake_players: Porting Lib Fake Players 2.1.875+1.19.2
			porting_lib_networking: Porting Lib Networking 2.1.875+1.19.2
		merenc: Merge Enchantments 3.2
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.2
		notenoughanimations: NotEnoughAnimations 1.7.1
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				cardinal-components-base: Cardinal Components API (base) 5.0.1
				cardinal-components-entity: Cardinal Components API (entities) 5.0.1
				playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		origins-classes: Origins: Classes 1.4.0
		pehkui: Pehkui 3.7.12+1.14.4-1.20.4
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		record_days_survived: Record Days Survived 1.3
		resourcefullib: Resourceful Lib 1.1.24
		rhino: Rhino 1902.2.3-build.284
		rpg_origins: RPG Origins 1.3.0
		skinlayers3d: 3d-Skin-Layers 1.6.2
		smartbrainlib: SmartBrainLib 1.9
		smoothchunk: Smooth chunk save Mod 1.19.2-3.5
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spiderstpo: Spiders 2.0 1.19.2-2.0.3
		sussyendereyes: Sussy Ender Eyes 1.0.1
		terrablender: TerraBlender 2.0.1.136
		totw_additions: Towers of the Wild: Additions 1.2.4
		totw_modded: Towers Of The Wild: Modded fabric-1.0.3-1.19.2
		touhouorigins: Touhou Origins 0.8.3-1.19.2
			apugli: Apugli 1.11.2+1.19-fabric
				midnightlib: MidnightLib 1.0.0
		veinmining: Vein Mining 1.1.3+1.19.2
			spectrelib: SpectreLib 0.12.6+1.19.2
		vivecraft: Vivecraft 1.19.2-1.1.9
			org_lwjgl_lwjgl-openvr: lwjgl-openvr 3.3.1
			org_lwjgl_lwjgl-openvr_natives-linux: lwjgl-openvr 3.3.1
			org_lwjgl_lwjgl-openvr_natives-macos: lwjgl-openvr 3.3.1
			org_lwjgl_lwjgl-openvr_natives-windows: lwjgl-openvr 3.3.1
		voidfog: Void Fog 2.7.1
		watching: From The Fog 1.9.1
		xaerominimap: Xaero's Minimap 24.0.1
	Loaded Shaderpack: BSL_v8.2.08(1).zip
		Profile: ULTRA (+7 options changed by user)
	Launched Version: fabric-loader-0.15.7-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.29, NVIDIA Corporation
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700H
```

**Comment by TalonFloof** [comment]
This is an old version of the mod, I don't maintain this version anymore, nor will I be accepting issues for it
